### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by malamili**

### CODE REVIEW

**Comment by gvdent** [comment]
One general question: Instead of the `cycle` of a service, should the swagger `info.version` value be used? That denotes the version of the interface, so seems like a clearer indication of whether an update is needed instead.

**Comment by malamili** [comment]
> One general question: Instead of the `cycle` of a service, should the swagger `info.version` value be used? That denotes the version of the interface, so seems like a clearer indication of whether an update is needed instead.

Services can call `/apply` how often they want. The `cycle` is supposed to be same during a service start and stop, so it is used to denote that a service hasn't restarted if it is the same, therefore we don't even need to check the swagger file. When the 'cycle' changes, we can assume the service restarted, and so we would check the swagger `info.version` to test for changes. Without `cycle`, we would have to check the swagger `info.version` each time a call to `/apply` takes place, which is unnecessary overhead.

**Review by gvdent — APPROVED** [review]
It seems to me that instead of sending 'cycle' services could send their own swagger file version, so no additional calls are needed, restarts without swagger file updates don't cause additional calls, and the version is more interesting info than an arbitrary cycle value.

But you've thought about this more than I have ;)

**Comment by malamili** [comment]
Resolved cycle by using swagger version

**Pull request merged**
